---
- name: Gather minimal facts
  setup:
    gather_subset: '!all'

- name: 检查 kuboard spray 版本
  run_once: true
  block:
    - name: 检查是否检测到 kuboardspray_version
      run_once: true
      fail:
        msg:
          - "资源包不支持当前 kuboardspray 版本" 
          - "请升级 kuboardspray 到最新版本 https://kuboard-spray.cn/support/change-log/v1.html"
      when:
        - kuboardspray_version is not defined

    - name: wrap kuboardspray_version
      set_fact:
        kuboardspray_version_wrapper: "{{ kuboardspray_version }}-w"

    - name: 读取资源包要求的最低 kuboardspray 版本
      shell: "cat package.yaml | shyaml get-value metadata.kuboard_spray_version.min"
      delegate_to: localhost
      args:
        chdir: "{{ playbook_dir }}"
      register: kuboardspray_min_version

    - name: "检查是否满足资源包对 kuboardspray 版本的最低要求 {{ kuboardspray_version }} >= {{ kuboardspray_min_version.stdout }}"
      assert:
        msg:
          - "资源包要求 kuboardspray 的版本不能低于 {{kuboardspray_min_version.stdout}}，当前 kuboardspray 版本为 {{ kuboardspray_version }}"
          - "建议升级 kuboardspray 到最新版本 https://kuboard-spray.cn/support/change-log/v1.html"
        that:
          - kuboardspray_version_wrapper is version(kuboardspray_min_version.stdout, operator='ge')

- name: 读取资源包支持的 CPU 架构
  shell: "cat package.yaml | shyaml get-value data.kubernetes.image_arch"
  delegate_to: localhost
  args:
    chdir: "{{ playbook_dir }}"
  register: kuboardspray_image_arch

- name: "检查是否支持此节点的 CPU 架构 {{ host_architecture }}"
  assert:
    msg:
      - "当前资源包支持 {{ kuboardspray_image_arch.stdout }}，不支持此节点的 CPU 架构: {{ host_architecture }}"
      - "请确保 kuboard-spray 所在机器的 CPU 架构与节点机器的 CPU 架构相同"
    that:
      - host_architecture == kuboardspray_image_arch.stdout

- name: 读取资源包支持的操作系统列表
  shell: "cat package.yaml | shyaml get-value metadata.supported_os"
  delegate_to: localhost
  args:
    chdir: "{{ playbook_dir }}"
  register: kuboardspray_supported_os

- set_fact:
    kuboardspray_supported_os_versions: "{{kuboardspray_supported_os.stdout | from_yaml | selectattr('distribution', '==', ansible_distribution)}}"

- name: "检查是否支持此操作系统 {{ ansible_distribution }} {{ ansible_distribution_version }}"
  assert:
    msg:
      - "当前资源包不支持此操作系统: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "当前资源包支持的操作系统有: {{ kuboardspray_supported_os.stdout | from_yaml }}"
    that:
      - kuboardspray_supported_os_versions|length > 0
      - ansible_distribution_version in kuboardspray_supported_os_versions[0].versions

- name: "检查是否为操作系统 {{ ansible_distribution }} 选择了软件源"
  assert:
    msg:
      - "请在『全局设置』『软件源』中勾选 {{ ansible_distribution }}"
    that:
      - "hostvars[inventory_hostname]['kuboardspray_repo_' + ansible_distribution | lower | regex_replace(' ', '_')] is defined"

# filter match the following variables:
# ansible_default_ipv4
# ansible_default_ipv6
# ansible_all_ipv4_addresses
# ansible_all_ipv6_addresses
- name: Gather necessary facts (network)
  setup:
    gather_subset: '!all,!min,network'
    filter: "ansible_*_ipv[46]*"

# filter match the following variables:
# ansible_memtotal_mb
# ansible_swaptotal_mb
- name: Gather necessary facts (hardware)
  setup:
    gather_subset: '!all,!min,hardware'
    filter: "ansible_*total_mb"
