kuboardspray:
  kubespray_version: master
  min_kuboard_spray_version: 'v1.0.0'
kubernetes:
  kube_version: 'v1.22.4'
  image_arch: amd64
  gcr_image_repo: 'gcr.io'
  kube_image_repo: 'k8s.gcr.io'
docker_engine:
  container_manager: 'containerd'
  version: '1.5.8'
  target: containerd_version

supported_os:
  - distribution: Ubuntu
    major_version: 20
    version: 20.04

etcd:
  etcd_version: 'v3.5.0'
  etcd_deployment_type: 'host'
dependency:
  - name: crun
    version: 1.3
    target: crun_version
  - name: runc
    version: 'v1.0.2'
    target: runc_version
  - name: cni-plugins
    version: 'v0.9.1'
    target: cni_version
  - name: crictl
    version: 'v1.22.0'
    target: crictl_version
  - name: nerdctl
    version: '0.14.0'
    target: nerdctl_version
  - name: nginx_image
    version: '1.19'
    target: nginx_image_tag
  - name: node_local_dns
    version: '1.21.1'
    target: nodelocaldns_version
  - name: coredns
    target: coredns_version
    version: 'v1.8.0'
  - name: cluster-proportional-autoscaler
    target: dnsautoscaler_version
    version: '1.8.5'
  - name: pause
    target: pod_infra_version
    version: '3.3'
cni:
  - name: calico
    version: 'v3.20.3'
    target: calico_version
  - name: flannel
    version: 'v0.14.0'
    target: flannel_version
addons:
  - name: helm
    included: false
    target: helm_enabled
    params:
      helm_version: "v3.7.1"
  - name: metrics_server
    included: true
    target: metrics_server_enabled
    params:
      metrics_server_version: "v0.5.0"
  - name: cephfs_provisioner
    included: false
    target: cephfs_provisioner_enabled
    params:
      cephfs_provisioner_image_tag: "v2.1.0-k8s1.11"
      csi_attacher_image_tag: "v2.2.0"
      csi_provisioner_image_tag: "v1.6.0"
      csi_snapshotter_image_tag: "v2.1.1"
      csi_resizer_image_tag: "v0.5.0"
      csi_node_driver_registrar_image_tag: "v1.3.0"
      csi_livenessprobe_image_tag: "v2.0.0"
  - name: local_path_provisioner
    included: false
    target: local_path_provisioner_enabled
    params:
      local_path_provisioner_image_tag: "v0.0.19"


download_keep_remote_cache: true
download_run_once: true
download_localhost: true
download_always_pull: false


# remove the following

# kata_containers_version: 2.2.3
# gvisor_version: 20210921

# calico_version: "v3.20.3"

# containerd_version: '1.5.8'

# helm_enabled: false

# registry_enabled: false

# metrics_server_enabled: true

# local_path_provisioner_enabled: false

# local_volume_provisioner_enabled: false

# cephfs_provisioner_enabled: false

# rbd_provisioner_enabled: false

# ingress_nginx_enabled: false

# ingress_alb_enabled: false

# cert_manager_enabled: false

# metallb_enabled: false

# argocd_enabled: false

# krew_enabled: false

# flannel_version: "v0.14.0"
# cni_version: "v0.9.1"
# weave_version: 2.8.1
# pod_infra_version: "3.3"
# cilium_version: "v1.9.11"
# kube_ovn_version: "v1.8.1"
# kube_router_version: "v1.3.2"
# multus_version: "v3.8"
# helm_version: "v3.7.1"
# nerdctl_version: "0.14.0"
# krew_version: "v0.4.2"

# coredns_version: "v1.8.0"
# nginx_image_tag: 1.19
# haproxy_image_tag: 2.3
# nodelocaldns_version: "1.21.1"
# dnsautoscaler_version: 1.8.5
# registry_image_tag: "2.7.1"
# registry_proxy_image_tag: "0.4"
# metrics_server_version: "v0.5.0"
# local_volume_provisioner_image_tag: "v2.4.0"
# cephfs_provisioner_image_tag: "v2.1.0-k8s1.11"
# rbd_provisioner_image_tag: "v2.1.1-k8s1.11"
# local_path_provisioner_image_tag: "v0.0.19"
# ingress_nginx_controller_image_tag: "v1.0.4"
# alb_ingress_image_tag: "v1.1.9"
# cert_manager_version: "v1.5.4"
# addon_resizer_version: "1.8.11"
# csi_attacher_image_tag: "v2.2.0"
# csi_provisioner_image_tag: "v1.6.0"
# csi_snapshotter_image_tag: "v2.1.1"
# csi_resizer_image_tag: "v0.5.0"
# csi_node_driver_registrar_image_tag: "v1.3.0"
# csi_livenessprobe_image_tag: "v2.0.0"

# dashboard_image_tag: "v2.4.0"