---

- hosts: all
  tasks:
    - set_fact:
        unsafe_show_logs: "{{ not (kuboardspray_no_log | default(true)) }}"

- name: deploy kube-bench
  hosts: target
  roles:
    - { role: kuboard-spray-facts }
    - { role: kubespray-defaults }
    - { role: deploy-kube-bench }