---

- hosts: all
  tasks:
    - set_fact:
        unsafe_show_logs: "{{ not (kuboardspray_no_log | default(true)) }}"

- name: 恢复 etcd 数据
  hosts: etcd
  gather_facts: False
  roles:
    - { role: kuboard-spray-facts }
    - { role: kubespray-defaults }
    - { role: restore-etcd }

