---

- hosts: all
  vars:
    unsafe_show_logs: "{{ not (kuboardspray_no_log|false) }}"

- name: 恢复 etcd 数据
  hosts: etcd
  gather_facts: False
  roles:
    - { role: kuboard-spray-facts }
    - { role: kubespray-defaults }
    - { role: restore-etcd }

