---
- name: Check ansible version
  import_playbook: 3rd/kubespray/ansible_version.yml

# content from 3rd/kubespray/facts.yml
- name: Gather facts
  gather_facts: no
  hosts: kube_control_plane[0],etcd[0],{{node}}
  roles:
    - { role: kuboard-spray-facts, when: reset_nodes|default(True)|bool }
    - { role: kubespray-defaults, when: reset_nodes|default(True)|bool }

# content from 3rd/kubespray/remove_node.yml
# - hosts: kube_control_plane[0]:etcd[0]
#   gather_facts: no
#   roles:
#     - { role: kubespray-defaults }

- hosts: "{{ node | default('kube_node') }}"
  gather_facts: no
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults, when: reset_nodes|default(True)|bool }
    - { role: remove-node/pre-remove, tags: pre-remove }
    - { role: remove-node/remove-etcd-node, when: inventory_hostname in groups.etcd }
    - { role: reset, tags: reset, when: reset_nodes|default(True)|bool }

# Currently cannot remove first master or etcd
- hosts: "{{ node | default('kube_control_plane[1:]:etcd[1:]') }}"
  gather_facts: no
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults, when: reset_nodes|default(True)|bool }
    - { role: remove-node/post-remove, tags: post-remove }
