---
- name: Check ansible version
  import_playbook: 3rd/kubespray/ansible_version.yml

- hosts: bastion[0]
  gather_facts: False
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"] }

- name: Config nginx proxy for apiserver
  gather_facts: False
  hosts: k8s_cluster
  roles:
    - { role: kubespray-defaults }
    - { role: kubernetes/node }

- name: Configure | Wait for nginx to restart
  gather_facts: False
  hosts: kube_node,!kube_control_plane
  tags: nginx
  tasks:

    - name: Configure | Wait for nginx to restart
      shell: "set -o pipefail && curl -ik https://localhost:6443/healthz | grep -v '\"apiVersion\":' > /dev/null"
      args:
        executable: /bin/bash
      register: nginx_is_healthy
      until: nginx_is_healthy.rc == 0
      retries: "25"
      delay: "5"
      changed_when: false
      check_mode: no
