---
# 由于始终通过镜像分发，因此我们不检查 ansible_version
# - name: Check ansible version
#   import_playbook: 3rd/kubespray/ansible_version.yml

- name: Gather facts
  gather_facts: False
  hosts: kube_control_plane:etcd
  any_errors_fatal: true
  roles:
    - { role: kuboard-spray-facts }
    - { role: kubespray-defaults }

- name: fix kube-apiserver.yaml
  hosts: kube_control_plane
  vars:
    etcd_hosts: "{{ groups['etcd'] | default(groups['kube_control_plane']) }}"
    etcd_access_addresses: |-
      {% for item in etcd_hosts -%}
        https://{{ hostvars[item]['etcd_access_address'] | default(hostvars[item]['ip'] | default(fallback_ips[item])) }}:2379{% if not loop.last %},{% endif %}
      {%- endfor %}
  tasks:
    - name: Update etcd-servers for apiserver
      lineinfile:
        dest: "{{ kube_config_dir }}/manifests/kube-apiserver.yaml"
        regexp: '^    - --etcd-servers='
        line: '    - --etcd-servers={{ etcd_access_addresses }}'
      when:
        - not etcd_kubeadm_enabled | default(false)
        - kuboardspray_node_action is not defined

    - name: print etcd-servers for apiserver
      debug:
        msg:
          - "文件 /etc/kubernetes/manifests/kube-apiserver.yaml 中的 --etcd-servers 参数已被替换为: {{ etcd_access_addresses }}"
      when:
        - kuboardspray_node_action is not defined

    - name: Configure | Wait for apiserver to be healthy
      shell: "set -o pipefail && kubectl get pods | grep -v 'did you specify the right host or port' > /dev/null"
      args:
        executable: /bin/bash
      register: kube_apiserver_is_healthy
      until: kube_apiserver_is_healthy.rc == 0
      retries: "25"
      delay: "5"
      changed_when: false
      check_mode: no
      when:
        - kuboardspray_node_action is not defined