---
- name: Check ansible version
  import_playbook: 3rd/kubespray/ansible_version.yml

# - name: Ensure compatibility with old groups
#   import_playbook: legacy_groups.yml

- hosts: bastion[0]
  gather_facts: False
  environment: "{{ proxy_disable_env }}"
  roles:
    - { role: kubespray-defaults }
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"] }

# - name: Gather facts
#   tags: always
#   import_playbook: 3rd/kubespray/facts.yml
- name: Gather facts
  gather_facts: False
  hosts: k8s_cluster:etcd:calico_rr
  roles:
    - { role: kuboard-spray-facts }

- name: Config nginx proxy for apiserver
  gather_facts: False
  hosts: kube_node
  roles:
    - { role: kubespray-defaults }
    - { role: kubernetes/node }
