---
- name: configuring centos /etc/yum.repos.d/CentOS-Base.repo
  template:
    src: etc/yum.repos.d/CentOS-Base.repo.j2
    dest: /etc/yum.repos.d/CentOS-Base.repo
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true
  register: kuboardspray_centos_repo_configured
  when: ansible_distribution == "CentOS" and kuboardspray_repo_centos != "AS_IS"

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
  when: kuboardspray_centos_repo_configured['changed']

- name: yum-clean-metadata
  command: yum makecache
  args:
    warn: no
  when: kuboardspray_centos_repo_configured['changed']