---
# containerd versions are only relevant for docker
containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.3.7': "{{ containerd_package }}=1.3.7-1"
  '1.3.9': "{{ containerd_package }}=1.3.9-1"
  '1.4.3': "{{ containerd_package }}=1.4.3-1"
  'stable': "{{ containerd_package }}=1.4.3-1"
  'edge': "{{ containerd_package }}=1.4.3-1"

docker_version: 19.03
docker_cli_version: 19.03

# https://download.docker.com/linux/debian/
docker_versioned_pkg:
  'latest': docker-ce
  '18.09': docker-ce=5:18.09.9~3-0~debian-{{ ansible_distribution_release|lower }}
  '19.03': docker-ce=5:19.03.15~3-0~debian-{{ ansible_distribution_release|lower }}
  'stable': docker-ce=5:19.03.15~3-0~debian-{{ ansible_distribution_release|lower }}
  'edge': docker-ce=5:19.03.15~3-0~debian-{{ ansible_distribution_release|lower }}

docker_cli_versioned_pkg:
  'latest': docker-ce-cli
  '18.09': docker-ce-cli=5:18.09.9~3-0~debian-{{ ansible_distribution_release|lower }}
  '19.03': docker-ce-cli=5:19.03.15~3-0~debian-{{ ansible_distribution_release|lower }}
  'stable': docker-ce-cli=5:19.03.15~3-0~debian-{{ ansible_distribution_release|lower }}
  'edge': docker-ce-cli=5:19.03.15~3-0~debian-{{ ansible_distribution_release|lower }}

docker_package_info:
  pkgs:
    - "{{ containerd_versioned_pkg[docker_containerd_version | string] }}"
    - "{{ docker_cli_versioned_pkg[docker_cli_version | string] }}"
    - "{{ docker_versioned_pkg[docker_version | string] }}"

docker_repo_key_info:
  url: '{{ docker_debian_repo_gpgkey }}'
  repo_keys:
    - '{{ docker_debian_repo_repokey }}'

docker_repo_info:
  repos:
    - >
      deb {{ docker_debian_repo_base_url }}
      {{ ansible_distribution_release|lower }}
      stable
