---
# containerd versions are only relevant for docker
containerd_versioned_pkg:
  'latest': "{{ containerd_package }}"
  '1.3.7': "{{ containerd_package }}-1.3.7-3.1.fc{{ ansible_distribution_major_version }}"
  '1.3.9': "{{ containerd_package }}-1.3.9-3.1.fc{{ ansible_distribution_major_version }}"
  '1.4.3': "{{ containerd_package }}-1.4.3-3.2.fc{{ ansible_distribution_major_version }}"
  '1.4.4': "{{ containerd_package }}-1.4.4-3.1.fc{{ ansible_distribution_major_version }}"
  '1.4.6': "{{ containerd_package }}-1.4.6-3.1.fc{{ ansible_distribution_major_version }}"
  '1.4.9': "{{ containerd_package }}-1.4.9-3.1.fc{{ ansible_distribution_major_version }}"
  '1.4.12': "{{ containerd_package }}-1.4.12-3.1.fc{{ ansible_distribution_major_version }}"
  'stable': "{{ containerd_package }}-1.4.12-3.1.fc{{ ansible_distribution_major_version }}"
  'edge': "{{ containerd_package }}-1.4.12-3.1.fc{{ ansible_distribution_major_version }}"

# https://docs.docker.com/install/linux/docker-ce/fedora/
# https://download.docker.com/linux/fedora/<fedora-version>/x86_64/stable/Packages/
docker_versioned_pkg:
  'latest': docker-ce
  '19.03': docker-ce-19.03.15-3.fc{{ ansible_distribution_major_version }}
  '20.10': docker-ce-20.10.11-3.fc{{ ansible_distribution_major_version }}
  'stable': docker-ce-20.10.11-3.fc{{ ansible_distribution_major_version }}
  'edge': docker-ce-20.10.11-3.fc{{ ansible_distribution_major_version }}

docker_cli_versioned_pkg:
  'latest': docker-ce-cli
  '19.03': docker-ce-cli-19.03.15-3.fc{{ ansible_distribution_major_version }}
  '20.10': docker-ce-cli-20.10.11-3.fc{{ ansible_distribution_major_version }}
  'stable': docker-ce-cli-20.10.11-3.fc{{ ansible_distribution_major_version }}
  'edge': docker-ce-cli-20.10.11-3.fc{{ ansible_distribution_major_version }}

docker_package_info:
  enablerepo: "docker-ce"
  pkgs:
    - "{{ containerd_versioned_pkg[docker_containerd_version | string] }}"
    - "{{ docker_cli_versioned_pkg[docker_cli_version | string] }}"
    - "{{ docker_versioned_pkg[docker_version | string] }}"
